; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html
[platformio]
default_envs = cyd 

[env:cyd]
;platform = espressif32
platform = https://github.com/pioarduino/platform-espressif32/releases/download/stable/platform-espressif32.zip
board = esp32dev
framework = arduino
monitor_speed = 115200
lib_deps = 
	bodmer/TFT_eSPI @ ^2.5.43
    bodmer/TJpg_Decoder
build_flags =
    -D BOARD_CYD=1
	-D USER_SETUP_LOADED=1
; DISPLAY
    -D DISPLAY_ENABLED=1
	-D ST7796_DRIVER=1
	-D TFT_WIDTH=320
	-D TFT_HEIGHT=480
	-D TFT_MISO=12
	-D TFT_MOSI=13
	-D TFT_SCLK=14
	-D TFT_CS=15
	-D TFT_DC=2
	-D TFT_RST=-1
	-D TFT_BL=27
	-D TFT_BACKLIGHT_ON=HIGH
	-D LOAD_GLCD=1
	-D LOAD_FONT2=1
    -D SPI_FREQUENCY=80000000
; TOUCH
    -D TOUCH_CS=33 
    -D SPI_READ_FREQUENCY=16000000
    -D SPI_TOUCH_FREQUENCY=2500000
; SDCARD
    -D SD_CS_PIN=5
    -D SD_SCLK=18
    -D SD_MISO=19
    -D SD_MOSI=23
; AUDIO
    -D AUDIO_DATA_PIN=26
    -D AUDIO_EN_PIN=4
; DEVELOPMENT
    -D SERIAL_DEBUG=1
;    -D CORE_DEBUG_LEVEL=5
;    -D CONFIG_HEAP_POISONING_COMPREHENSIVE=1
;    -D CONFIG_HEAP_TRACING=1
;    -D ARDUINO_LOOP_STACK_SIZE=16384


[env:jc]
platform = https://github.com/pioarduino/platform-espressif32/releases/download/stable/platform-espressif32.zip
board = JC3248W535C 
framework = arduino
monitor_speed = 115200
lib_deps = 
    moononournation/GFX Library for Arduino @ ^1.4.5
    bodmer/TJpg_Decoder
build_flags =
    -O2
	-D BOARD_JC3248=1
	-D ARDUINO_LOOP_STACK_SIZE=16384
	-D BOARD_HAS_PSRAM=1
; DISPLAY
    -D DISPLAY_ENABLED=1
    -D AXS15231B_DRIVER=1
	-D TFT_WIDTH=320
	-D TFT_HEIGHT=480
    -D TFT_BL=1
; SERIAL
	-D ARDUINO_USB_CDC_ON_BOOT=0
	-D ARDUINO_USB_MODE=1
; SDCARD
    -D SD_CS_PIN=5
    -D SD_SCLK=18
    -D SD_MISO=19
    -D SD_MOSI=23
; AUDIO
    -D AUDIO_DATA_PIN=26
    -D AUDIO_EN_PIN=4
; DEVELOPMENT
    -D SERIAL_DEBUG=1
;    -D CORE_DEBUG_LEVEL=5
;    -D CONFIG_HEAP_POISONING_COMPREHENSIVE=1
;    -D CONFIG_HEAP_TRACING=1
;    -D ARDUINO_LOOP_STACK_SIZE=16384
