[env:esp32dev]
platform = espressif32
board = esp32dev
build_flags = 
    -O2
    -fpack-struct=4
    -fPIC
    -mlongcalls
    -fno-jump-tables
    -nostartfiles
    -nodefaultlibs
    -Wl,-e,_start
    -Wl,-T,mdb.ld
    -Wl,--no-warn-rwx-segments
    -fno-tree-loop-distribute-patterns
    -fno-tree-switch-conversion
    -mtext-section-literals


extra_scripts = post:extract_bin.py
