[env:esp32dev]
platform = espressif32
board = esp32dev
build_flags =
    -Os
    -fPIC
    -mlongcalls
    -fno-jump-tables
    -nostartfiles
    -nodefaultlibs
    -Wl,-e,_start
    -Wl,-T,mdb.ld
    -Wl,--no-warn-rwx-segments
    -fno-tree-loop-distribute-patterns
    -fno-tree-switch-conversion
    -fno-toplevel-reorder
    -mtext-section-literals
    -mtarget-align
    -fno-merge-constants
    -save-temps=obj
extra_scripts = post:extract_bin.py
